name: Deploy ADF

on:
  push:
    branches:
      - adf_publish

permissions:
  id-token: write
  contents: read

jobs:
  deploy-testing:
    name: Deploy ADF to Testing
    runs-on: ubuntu-latest

    environment: testing

    steps:

      - name: Checkout adf_publish
        uses: actions/checkout@v4
        with:
          ref: adf_publish

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Pre-deployment
        uses: azure/powershell@v3
        with:
          azPSVersion: latest
          pwsh: true
          scriptType: filePath
          scriptPath: scripts/PrePostDeploymentScript.Ver2.ps1
          scriptArguments: >
            -ArmTemplate "ARMTemplateForFactory.json"
            -ArmTemplateParameters "ARMTemplateParametersForFactory.json"
            -ResourceGroupName "test-ci-cd-demo-rg"
            -DataFactoryName "test-ci-cd-demo-adf-y8"
            -PreDeployment $true
            -DeleteDeployment $false

      - name: Deploy ARM template
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: test-ci-cd-demo-rg
          template: ARMTemplateForFactory.json
          parameters: >
                ARMTemplateParametersForFactory.json
                factoryName=test-ci-cd-demo-adf-y8
          deploymentMode: Incremental

      - name: Post-deployment
        uses: azure/powershell@v3
        with:
          azPSVersion: latest
          pwsh: true
          scriptType: filePath
          scriptPath: scripts/PrePostDeploymentScript.Ver2.ps1
          scriptArguments: >
            -ArmTemplate "ARMTemplateForFactory.json"
            -ArmTemplateParameters "ARMTemplateParametersForFactory.json"
            -ResourceGroupName "test-ci-cd-demo-rg"
            -DataFactoryName "test-ci-cd-demo-adf-y8"
            -PreDeployment $false
            -DeleteDeployment $true